import sys
import json
import httpx

BASE_URL = "http://localhost:8000"

def run_tests():
    print("[START] STARTING NURSEWATCH AI END-TO-END VALIDATION TESTS...")
    
    # 1. LOGIN TEST
    print("\n--- 1. Testing Authentication ---")
    login_data = {"email": "nurse1@amrita.org", "password": "amrita123"}
    try:
        response = httpx.post(f"{BASE_URL}/auth/login", json=login_data, timeout=10.0)
        if response.status_code != 200:
            print(f"[ERROR] Login failed with status {response.status_code}: {response.text}")
            sys.exit(1)
        
        token = response.json().get("access_token")
        if not token:
            print("[ERROR] Access token missing in login response.")
            sys.exit(1)
        print("[OK] Login successful! Token retrieved.")
    except Exception as e:
        print(f"[ERROR] Login request error: {e}")
        sys.exit(1)
        
    headers = {"Authorization": f"Bearer {token}"}

    # 2. GET PATIENTS LIST
    print("\n--- 2. Fetching Patient List ---")
    try:
        response = httpx.get(f"{BASE_URL}/patients/", headers=headers, timeout=10.0)
        if response.status_code != 200:
            print(f"[ERROR] Failed to fetch patients list: {response.text}")
            sys.exit(1)
        patients = response.json()
        print(f"[OK] Patient list retrieved! Total patients: {len(patients)}")
        # Select patient 5 (Govind Patel)
        target_patient = None
        for p in patients:
            if p["full_name"] == "Govind Patel":
                target_patient = p
                break
        
        if not target_patient:
            print("[ERROR] Target patient 'Govind Patel' not found in database.")
            sys.exit(1)
        
        p_id = target_patient["id"]
        print(f"[OK] Found target patient: {target_patient['full_name']} (ID: {p_id})")
    except Exception as e:
        print(f"[ERROR] Patient list request error: {e}")
        sys.exit(1)

    # 3. ENTER VITALS & VALIDATE (AGENT 3, 5, 6, 7, 8)
    print("\n--- 3. Recording Vitals Round (NEWS2 & Alerts Agents) ---")
    # Enter a critical vital sign round to trigger warning systems
    vital_payload = {
        "patient_id": p_id,
        "shift": "evening",
        "systolic_bp": 135.0,
        "diastolic_bp": 85.0,
        "heart_rate": 105.0,     # elevated hr
        "respiratory_rate": 26.0, # high rr -> score 3
        "spo2": 89.0,             # low spo2 (copd) -> score 2
        "temperature": 38.5,      # elevated temp
        "consciousness": "Alert",
        "blood_glucose": 210.0,
        "source": "nurse_manual"
    }
    try:
        response = httpx.post(f"{BASE_URL}/vitals/", json=vital_payload, headers=headers, timeout=15.0)
        if response.status_code != 200:
            print(f"[ERROR] Failed to record vitals: {response.text}")
            sys.exit(1)
        
        vital_result = response.json()
        news2_score = vital_result.get("news2_score")
        risk_level = vital_result.get("risk_level")
        print(f"[OK] Vitals recorded successfully!")
        print(f"   Calculated NEWS2 score: {news2_score}")
        print(f"   Calculated Risk level: {risk_level}")
        if news2_score is None:
            print("[ERROR] NEWS2 Score calculation failed (is None).")
            sys.exit(1)
    except Exception as e:
        print(f"[ERROR] Vitals entry request error: {e}")
        sys.exit(1)

    # 4. GENERATE SBAR SUMMARY (AGENT 9 - GEMINI)
    print("\n--- 4. Generating SBAR Handover (Gemini AI Agent) ---")
    try:
        response = httpx.post(f"{BASE_URL}/sbar/generate/{p_id}", headers=headers, timeout=30.0)
        if response.status_code != 200:
            print(f"[ERROR] SBAR generation failed: {response.text}")
            sys.exit(1)
            
        sbar = response.json()
        print("[OK] SBAR Handover generated successfully!")
        print(f"   Generated by: {sbar.get('generated_by')}")
        print(f"   Situation: {sbar.get('situation')[:120]}...")
        print(f"   Background: {sbar.get('background')[:120]}...")
        print(f"   Assessment: {sbar.get('assessment')[:120]}...")
        print(f"   Recommendation: {sbar.get('recommendation')[:120]}...")
        
        if "gemini" not in sbar.get("generated_by", "").lower():
            print("[WARN] Warning: SBAR fell back to template instead of real Gemini output.")
    except Exception as e:
        print(f"[ERROR] SBAR request error: {e}")
        sys.exit(1)

    # 5. MULTILINGUAL TRANSLATION (AGENT 4 - TAMIL/HINDI TRANSLATION)
    print("\n--- 5. Testing SBAR Tamil & Hindi Translation ---")
    try:
        # Tamil
        response = httpx.post(f"{BASE_URL}/sbar/generate/{p_id}?lang=tamil", headers=headers, timeout=30.0)
        if response.status_code != 200:
            print(f"[ERROR] Tamil translation failed: {response.text}")
            sys.exit(1)
        tamil_sbar = response.json()
        print("[OK] Tamil translation request successful!")
        print(f"   Generated by: {tamil_sbar.get('generated_by')}")
        
        # Hindi
        response = httpx.post(f"{BASE_URL}/sbar/generate/{p_id}?lang=hindi", headers=headers, timeout=30.0)
        if response.status_code != 200:
            print(f"[ERROR] Hindi translation failed: {response.text}")
            sys.exit(1)
        hindi_sbar = response.json()
        print("[OK] Hindi translation request successful!")
        print(f"   Generated by: {hindi_sbar.get('generated_by')}")
    except Exception as e:
        print(f"[ERROR] Translation request error: {e}")
        sys.exit(1)

    # 6. RAG CLINICAL ASSISTANT
    print("\n--- 6. Testing Patient Clinical RAG Chatbot (Gemini RAG Agent) ---")
    question_payload = {
        "question": "What comorbidities does Govind Patel have and what is his latest SpO2?"
    }
    try:
        response = httpx.post(f"{BASE_URL}/innovations/patients/{p_id}/ask", json=question_payload, headers=headers, timeout=30.0)
        if response.status_code != 200:
            print(f"[ERROR] RAG query failed: {response.text}")
            sys.exit(1)
        rag_res = response.json()
        print("[OK] RAG Clinical Chatbot response successful!")
        # Use json dumps to handle non-ascii chars if present
        print("   AI Answer: " + json.dumps(rag_res.get('answer')))
    except Exception as e:
        print(f"[ERROR] RAG request error: {e}")
        sys.exit(1)

    print("\n[SUCCESS] ALL END-TO-END VALIDATION TESTS COMPLETED SUCCESSFULLY!")

if __name__ == "__main__":
    run_tests()
