/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as RoleRouteImport } from './routes/role'
import { Route as NurseRouteImport } from './routes/nurse'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NurseIndexRouteImport } from './routes/nurse.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as NurseTasksRouteImport } from './routes/nurse.tasks'
import { Route as NurseProfileRouteImport } from './routes/nurse.profile'
import { Route as NursePatientsRouteImport } from './routes/nurse.patients'
import { Route as NurseNotificationsRouteImport } from './routes/nurse.notifications'
import { Route as LoginNurseRouteImport } from './routes/login.nurse'
import { Route as LoginAdminRouteImport } from './routes/login.admin'
import { Route as AdminWardsRouteImport } from './routes/admin.wards'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPatientsRouteImport } from './routes/admin.patients'
import { Route as AdminNursesRouteImport } from './routes/admin.nurses'
import { Route as AdminAlertsRouteImport } from './routes/admin.alerts'
import { Route as NurseSbarIndexRouteImport } from './routes/nurse.sbar.index'
import { Route as NurseVitalsPatientIdRouteImport } from './routes/nurse.vitals.$patientId'
import { Route as NurseSbarPatientIdRouteImport } from './routes/nurse.sbar.$patientId'
import { Route as NursePatientPatientIdRouteImport } from './routes/nurse.patient.$patientId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleRoute = RoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => rootRouteImport,
} as any)
const NurseRoute = NurseRouteImport.update({
  id: '/nurse',
  path: '/nurse',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NurseIndexRoute = NurseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NurseRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const NurseTasksRoute = NurseTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => NurseRoute,
} as any)
const NurseProfileRoute = NurseProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => NurseRoute,
} as any)
const NursePatientsRoute = NursePatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => NurseRoute,
} as any)
const NurseNotificationsRoute = NurseNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => NurseRoute,
} as any)
const LoginNurseRoute = LoginNurseRouteImport.update({
  id: '/login/nurse',
  path: '/login/nurse',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginAdminRoute = LoginAdminRouteImport.update({
  id: '/login/admin',
  path: '/login/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWardsRoute = AdminWardsRouteImport.update({
  id: '/wards',
  path: '/wards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatientsRoute = AdminPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNursesRoute = AdminNursesRouteImport.update({
  id: '/nurses',
  path: '/nurses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertsRoute = AdminAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AdminRoute,
} as any)
const NurseSbarIndexRoute = NurseSbarIndexRouteImport.update({
  id: '/sbar/',
  path: '/sbar/',
  getParentRoute: () => NurseRoute,
} as any)
const NurseVitalsPatientIdRoute = NurseVitalsPatientIdRouteImport.update({
  id: '/vitals/$patientId',
  path: '/vitals/$patientId',
  getParentRoute: () => NurseRoute,
} as any)
const NurseSbarPatientIdRoute = NurseSbarPatientIdRouteImport.update({
  id: '/sbar/$patientId',
  path: '/sbar/$patientId',
  getParentRoute: () => NurseRoute,
} as any)
const NursePatientPatientIdRoute = NursePatientPatientIdRouteImport.update({
  id: '/patient/$patientId',
  path: '/patient/$patientId',
  getParentRoute: () => NurseRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/nurse': typeof NurseRouteWithChildren
  '/role': typeof RoleRoute
  '/welcome': typeof WelcomeRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/nurses': typeof AdminNursesRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/wards': typeof AdminWardsRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/nurse': typeof LoginNurseRoute
  '/nurse/notifications': typeof NurseNotificationsRoute
  '/nurse/patients': typeof NursePatientsRoute
  '/nurse/profile': typeof NurseProfileRoute
  '/nurse/tasks': typeof NurseTasksRoute
  '/admin/': typeof AdminIndexRoute
  '/nurse/': typeof NurseIndexRoute
  '/nurse/patient/$patientId': typeof NursePatientPatientIdRoute
  '/nurse/sbar/$patientId': typeof NurseSbarPatientIdRoute
  '/nurse/vitals/$patientId': typeof NurseVitalsPatientIdRoute
  '/nurse/sbar/': typeof NurseSbarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/role': typeof RoleRoute
  '/welcome': typeof WelcomeRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/nurses': typeof AdminNursesRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/wards': typeof AdminWardsRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/nurse': typeof LoginNurseRoute
  '/nurse/notifications': typeof NurseNotificationsRoute
  '/nurse/patients': typeof NursePatientsRoute
  '/nurse/profile': typeof NurseProfileRoute
  '/nurse/tasks': typeof NurseTasksRoute
  '/admin': typeof AdminIndexRoute
  '/nurse': typeof NurseIndexRoute
  '/nurse/patient/$patientId': typeof NursePatientPatientIdRoute
  '/nurse/sbar/$patientId': typeof NurseSbarPatientIdRoute
  '/nurse/vitals/$patientId': typeof NurseVitalsPatientIdRoute
  '/nurse/sbar': typeof NurseSbarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/nurse': typeof NurseRouteWithChildren
  '/role': typeof RoleRoute
  '/welcome': typeof WelcomeRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/nurses': typeof AdminNursesRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/wards': typeof AdminWardsRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/nurse': typeof LoginNurseRoute
  '/nurse/notifications': typeof NurseNotificationsRoute
  '/nurse/patients': typeof NursePatientsRoute
  '/nurse/profile': typeof NurseProfileRoute
  '/nurse/tasks': typeof NurseTasksRoute
  '/admin/': typeof AdminIndexRoute
  '/nurse/': typeof NurseIndexRoute
  '/nurse/patient/$patientId': typeof NursePatientPatientIdRoute
  '/nurse/sbar/$patientId': typeof NurseSbarPatientIdRoute
  '/nurse/vitals/$patientId': typeof NurseVitalsPatientIdRoute
  '/nurse/sbar/': typeof NurseSbarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/nurse'
    | '/role'
    | '/welcome'
    | '/admin/alerts'
    | '/admin/nurses'
    | '/admin/patients'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/wards'
    | '/login/admin'
    | '/login/nurse'
    | '/nurse/notifications'
    | '/nurse/patients'
    | '/nurse/profile'
    | '/nurse/tasks'
    | '/admin/'
    | '/nurse/'
    | '/nurse/patient/$patientId'
    | '/nurse/sbar/$patientId'
    | '/nurse/vitals/$patientId'
    | '/nurse/sbar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/role'
    | '/welcome'
    | '/admin/alerts'
    | '/admin/nurses'
    | '/admin/patients'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/wards'
    | '/login/admin'
    | '/login/nurse'
    | '/nurse/notifications'
    | '/nurse/patients'
    | '/nurse/profile'
    | '/nurse/tasks'
    | '/admin'
    | '/nurse'
    | '/nurse/patient/$patientId'
    | '/nurse/sbar/$patientId'
    | '/nurse/vitals/$patientId'
    | '/nurse/sbar'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/nurse'
    | '/role'
    | '/welcome'
    | '/admin/alerts'
    | '/admin/nurses'
    | '/admin/patients'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/wards'
    | '/login/admin'
    | '/login/nurse'
    | '/nurse/notifications'
    | '/nurse/patients'
    | '/nurse/profile'
    | '/nurse/tasks'
    | '/admin/'
    | '/nurse/'
    | '/nurse/patient/$patientId'
    | '/nurse/sbar/$patientId'
    | '/nurse/vitals/$patientId'
    | '/nurse/sbar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  NurseRoute: typeof NurseRouteWithChildren
  RoleRoute: typeof RoleRoute
  WelcomeRoute: typeof WelcomeRoute
  LoginAdminRoute: typeof LoginAdminRoute
  LoginNurseRoute: typeof LoginNurseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role': {
      id: '/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof RoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nurse': {
      id: '/nurse'
      path: '/nurse'
      fullPath: '/nurse'
      preLoaderRoute: typeof NurseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nurse/': {
      id: '/nurse/'
      path: '/'
      fullPath: '/nurse/'
      preLoaderRoute: typeof NurseIndexRouteImport
      parentRoute: typeof NurseRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/nurse/tasks': {
      id: '/nurse/tasks'
      path: '/tasks'
      fullPath: '/nurse/tasks'
      preLoaderRoute: typeof NurseTasksRouteImport
      parentRoute: typeof NurseRoute
    }
    '/nurse/profile': {
      id: '/nurse/profile'
      path: '/profile'
      fullPath: '/nurse/profile'
      preLoaderRoute: typeof NurseProfileRouteImport
      parentRoute: typeof NurseRoute
    }
    '/nurse/patients': {
      id: '/nurse/patients'
      path: '/patients'
      fullPath: '/nurse/patients'
      preLoaderRoute: typeof NursePatientsRouteImport
      parentRoute: typeof NurseRoute
    }
    '/nurse/notifications': {
      id: '/nurse/notifications'
      path: '/notifications'
      fullPath: '/nurse/notifications'
      preLoaderRoute: typeof NurseNotificationsRouteImport
      parentRoute: typeof NurseRoute
    }
    '/login/nurse': {
      id: '/login/nurse'
      path: '/login/nurse'
      fullPath: '/login/nurse'
      preLoaderRoute: typeof LoginNurseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/admin': {
      id: '/login/admin'
      path: '/login/admin'
      fullPath: '/login/admin'
      preLoaderRoute: typeof LoginAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wards': {
      id: '/admin/wards'
      path: '/wards'
      fullPath: '/admin/wards'
      preLoaderRoute: typeof AdminWardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patients': {
      id: '/admin/patients'
      path: '/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AdminPatientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/nurses': {
      id: '/admin/nurses'
      path: '/nurses'
      fullPath: '/admin/nurses'
      preLoaderRoute: typeof AdminNursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alerts': {
      id: '/admin/alerts'
      path: '/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAlertsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/nurse/sbar/': {
      id: '/nurse/sbar/'
      path: '/sbar'
      fullPath: '/nurse/sbar/'
      preLoaderRoute: typeof NurseSbarIndexRouteImport
      parentRoute: typeof NurseRoute
    }
    '/nurse/vitals/$patientId': {
      id: '/nurse/vitals/$patientId'
      path: '/vitals/$patientId'
      fullPath: '/nurse/vitals/$patientId'
      preLoaderRoute: typeof NurseVitalsPatientIdRouteImport
      parentRoute: typeof NurseRoute
    }
    '/nurse/sbar/$patientId': {
      id: '/nurse/sbar/$patientId'
      path: '/sbar/$patientId'
      fullPath: '/nurse/sbar/$patientId'
      preLoaderRoute: typeof NurseSbarPatientIdRouteImport
      parentRoute: typeof NurseRoute
    }
    '/nurse/patient/$patientId': {
      id: '/nurse/patient/$patientId'
      path: '/patient/$patientId'
      fullPath: '/nurse/patient/$patientId'
      preLoaderRoute: typeof NursePatientPatientIdRouteImport
      parentRoute: typeof NurseRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAlertsRoute: typeof AdminAlertsRoute
  AdminNursesRoute: typeof AdminNursesRoute
  AdminPatientsRoute: typeof AdminPatientsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminWardsRoute: typeof AdminWardsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlertsRoute: AdminAlertsRoute,
  AdminNursesRoute: AdminNursesRoute,
  AdminPatientsRoute: AdminPatientsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminWardsRoute: AdminWardsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface NurseRouteChildren {
  NurseNotificationsRoute: typeof NurseNotificationsRoute
  NursePatientsRoute: typeof NursePatientsRoute
  NurseProfileRoute: typeof NurseProfileRoute
  NurseTasksRoute: typeof NurseTasksRoute
  NurseIndexRoute: typeof NurseIndexRoute
  NursePatientPatientIdRoute: typeof NursePatientPatientIdRoute
  NurseSbarPatientIdRoute: typeof NurseSbarPatientIdRoute
  NurseVitalsPatientIdRoute: typeof NurseVitalsPatientIdRoute
  NurseSbarIndexRoute: typeof NurseSbarIndexRoute
}

const NurseRouteChildren: NurseRouteChildren = {
  NurseNotificationsRoute: NurseNotificationsRoute,
  NursePatientsRoute: NursePatientsRoute,
  NurseProfileRoute: NurseProfileRoute,
  NurseTasksRoute: NurseTasksRoute,
  NurseIndexRoute: NurseIndexRoute,
  NursePatientPatientIdRoute: NursePatientPatientIdRoute,
  NurseSbarPatientIdRoute: NurseSbarPatientIdRoute,
  NurseVitalsPatientIdRoute: NurseVitalsPatientIdRoute,
  NurseSbarIndexRoute: NurseSbarIndexRoute,
}

const NurseRouteWithChildren = NurseRoute._addFileChildren(NurseRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  NurseRoute: NurseRouteWithChildren,
  RoleRoute: RoleRoute,
  WelcomeRoute: WelcomeRoute,
  LoginAdminRoute: LoginAdminRoute,
  LoginNurseRoute: LoginNurseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
